language: node_js

node_js:
  - '6.10'
  - '8'

install:
  - yarn install

script:
  - yarn run lint
  - yarn run test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage

deploy:
  provider: npm
  email: accounts@acloud.guru
  api_key:
    secure: TrEeZUkaXq8nvgO+3Ql6Jws9Lqi6KXBgRBv5JxCZ7G4DMLaNXvYnnqRrboIK6s5E3GDkPkvfZBydNN5hFLYJV8ORFOlZ3HiL6gTEkOjD44vxuz2FwaOXZM7YhVqD0Ia0mE68eVc5a/eSOAt8HK3uGEvpYCEFemX8zu4FAszwj83b7ewusBmPAyoVGv8VQZSe2Mkls8flh6woC+zM9RIqX78mEcfTrkZKH/FIsnFCG4MVSLKQk2IVuujJajVQ6uSToHmbiw2orGItsDaoYRFtpWiGdl5PSU5uTmB+SjTv/N7LbBwThkybArXthEhMCsPCLGXPU7aISa1E2q0bwxik8s3gmTGnMan6Qqu1aIX5iTk/AYLDOMKJXPPyGbozNCuYY5Z8s2Y7q9JZIkcGBryxXYIqgSg3Gy0rcU/ZHORVAZ2Dy3iEebG3b0F56PIEwWWPs9dWy72hTbfSEIV7qonNq+i5IjhoVjP0ha9oaseZqOs1BiKVSHMoTPq+gt13YlEfdK9X4tah0ErlpbjD3w4DBtiYi9qALX0B/4OSEMlh6vd33eN/fXPkw+EEbGrYp8Tk/z8ZDWZIfnHX3aYXZ0yAqJViS8n81NU4XX9nV22BtU2pGIyN1xPD1df6ozjw5YKZf1y7qzDrXHcmRuFrHSpc2xCCBPqgHcfShEzg2fsfupI=
  on:
    tags: true
    repo: ACloudGuru/serverless-plugin-dynamo-autoscaling
    branch: master
    node: '6.10'
